export const COUNT_WORDS=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen','twenty'];
export const COUNTRIES=['UK','Canada','USA','China'];
export const countryPhrase=c=>['UK','USA'].includes(c)?`the ${c}`:c;
export const GUESTS=[{id:'amy',name:'Amy',country:'UK',sprite:'schoolgirl',role:'student',pronoun:'she'},{id:'mike',name:'Mike',country:'Canada',sprite:'schoolboy',role:'student',pronoun:'he'},{id:'sarah',name:'Sarah',country:'USA',sprite:'schoolgirl',role:'student',pronoun:'she'},{id:'binbin',name:'Binbin',country:'China',sprite:'brother',role:'student',pronoun:'he'}];
export const FAMILY=['father','mother','grandfather','grandmother','brother','sister'];
export const FRUITS=['pear','apple','orange','banana','watermelon','strawberry','grape'];
export const plural=w=>w==='strawberry'?'strawberries':w+'s';
export const FRUIT_ORDERS=[{who:'fox',name:'Fox',items:['apple','pear','orange']},{who:'cat',name:'Cat',items:['banana','grape','strawberry']},{who:'bird',name:'Bird',items:['watermelon']}];
export const TRAITS=[{word:'tall',animal:'giraffe'},{word:'short',animal:'bear'},{word:'fat',animal:'panda'},{word:'thin',animal:'monkey'},{word:'big',animal:'elephant'},{word:'small',animal:'cat'},{word:'long',animal:'giraffe'}];
export const FEATURES=['big body','long nose','small eyes','big ears','short tail'];
export const PLACES=['on the desk','in the desk','under the desk','on the chair','under the chair','in the box','on the box'];
export const TOYS=[{word:'car',place:'under the chair',destination:'in the box'},{word:'cap',place:'in the box',destination:'in the box'},{word:'ball',place:'on the desk',destination:'under the desk'},{word:'boat',place:'under the desk',destination:'on the desk'},{word:'map',place:'on the chair',destination:'on the box'}];
export const GATES=[{x:280,y:390,name:'迎新桥',word:'China'},{x:520,y:280,name:'家庭桥',word:'family'},{x:780,y:410,name:'动物桥',word:'giraffe'}];
const entry=(id,unit,title,name,pages,kind,goals,words,expressions,phonics,reward,rewardSprite,hint)=>({id,book:'lower',unit,title,name,pages,kind,goals,words,expressions,phonics,reward,rewardSprite,hint,letters:''});
export const LOWER_CHAPTERS=[
 entry('l1','Unit 1','Welcome back to school!','春日迎新站','2–11','welcome-school',['给四位伙伴盖国家章','完成伙伴身份牌','介绍自己和新朋友'],[...COUNTRIES,'she','student','pupil','he','teacher','boy','and','girl','new','friend','today'],['Welcome back to school!','Nice to see you again.','Where are you from?',"I’m from China.","This is Amy. She’s a student."],['cat','bag','hand','dad'],'国际友谊护照','China','把国家章和身份牌送到伙伴的迎新卡，再用英语介绍自己和新朋友。'),
 entry('l2','Unit 2','My family','家庭相册侦探','12–21','family-quest',['探索并拍到六位家人','拼好家庭相册','介绍家人并回答问题'],['father','dad','man','woman','mother','sister','brother','grandmother','grandma','grandfather','grandpa','family'],["Who’s that man?","He’s my father.","Who’s that woman?","She’s my mother.","Is she your mother?","Yes, she is. / No, she isn’t."],['ten','pen','leg','red'],'Leo一家相册','family','这是虚构的 Leo 一家。点击家人走近，再点一次或按 E 拍照；把照片拖回对应相册。'),
 entry('l3','Unit 3','At the zoo','动物特征研究所','22–31','zoo-lab',['记录七种动物特征','搭好五张特征拼图','用英语描述动物'],['thin','fat','tall','short','long','small','big','giraffe','so','children','tail'],['Look at that giraffe!',"It’s so tall.",'It has a long nose.','It has small eyes and big ears.'],['big','pig','six','milk'],'动物观察勋章','giraffe','把特征词拖给合适的动物，再完成大象的身体特征拼图；观察后说出发现。'),
 entry('lr1','Recycle 1','Spring adventure','春游通行证','32–35','spring-gates',['通过迎新桥','通过家庭桥','通过动物桥'],[...COUNTRIES,...FAMILY,...TRAITS.map(t=>t.word)],['Where are you from?',"I’m from China.","He’s my father.",'It has a long nose.'],['cat','bag','ten','red','big','pig'],'春游通行证','map','走到三座桥的标记。说出对应英语，再点桥标记或按 E 盖章，解锁下一段路。'),
 entry('l4','Unit 4','Where is my car?','玩具寻宝队','36–45','toy-hunt',['找回并说出五件玩具的位置','按新位置收拾五件玩具','确认帽子藏在哪里'],['on','in','under','chair','desk','cap','ball','car','boat','map','toy','box'],['Where is my car?',"It’s under the chair.",'Is it in the box?',"Yes, it is. / No, it isn’t.",'Have a good time!'],['dog','box','orange','body'],'玩具藏宝图','car','点击家具的位置走近，再点一次或按 E 搜索。找到玩具后说出原位置，再把玩具搬到新位置。'),
 entry('l5','Unit 5','Do you like pears?','果园采集小队','46–55','orchard',['亲手采集七种水果','完成三位朋友的水果订单','表达喜好并开口要水果'],[...FRUITS,'buy','fruit'],['Do you like pears?','Yes, I do. / No, I don’t.','I like apples.','I don’t like grapes.','Can I have some bananas?','Here you are.'],['fun','run','duck','under'],'果园分享篮','apple','先走近水果，点击或按 E 采摘；篮里的水果才能拖给客人。说出喜好，伙伴会送你选的水果。'),
 entry('l6','Unit 6','How many?','风筝计数实验室','56–65','kite-lab',['数清天空风筝，排除小黑鸟','收集十六支蜡笔并报数量','制作一组十一至二十只风筝'],[...COUNT_WORDS.slice(11),'kite','beautiful'],['How many kites do you see?','I see twelve.','The black one is a bird!','How many crayons do you have?','I have sixteen.','Open it and see!'],['hand','legs','ten','dog','duck','big'],'风筝实验室证书','kite','先点击标记每只风筝，小黑鸟不算！再收集蜡笔，最后选英文数量并逐只放飞风筝。'),
 entry('lr2','Recycle 2','Snakes and ladders','森林棋盘大冒险','66–69','board-adventure',['走到棋盘终点','获得十三根香蕉和二十颗葡萄','向伙伴报告水果数量'],[...FRUITS,...TOYS.map(t=>t.word),...COUNT_WORDS.slice(11),'on','in','under'],['Do you like bananas?',"It’s under the chair.",'I see thirteen bananas.','I have twenty grapes.'],['fat','cat','red','pen','big','pig','hot','dog','fun','duck'],'三年级全册探险奖章','banana','掷骰子遇到喜好、位置或数量挑战。说对才能前进；梯子向上，藤蔓向下。到终点还可继续探险集齐水果。')
];
const phonicsPages={l1:'6',l2:'16',l3:'26',lr1:'34–35',l4:'40',l5:'50',l6:'60',lr2:'69'};
LOWER_CHAPTERS.forEach(c=>c.phonicsPages=phonicsPages[c.id]);
const n=(key,npc,help,examples,mode,extra={})=>({key,npc,help,examples,mode,lower:true,...extra});
export function boardChallenge(s){const kind=s.board.turn%3;if(kind===0)return {mode:'taste',npc:'Do you like bananas?',examples:['Yes, I do.',"No, I don't."]};if(kind===1)return {mode:'location',npc:'Where is my car?',examples:["It's under the chair."],expected:'under the chair'};return {mode:'number',npc:'How many bananas do you see?',examples:['I see thirteen bananas.'],expected:13,prefix:'see'};}
export function lowerDialogue(id,s,profile){const t=s.talks||{};
 switch(id){
 case 'l1':return !t.origin?n('origin','Where are you from?','用完整句子告诉伙伴你来自哪里。',COUNTRIES.map(c=>`I'm from ${countryPhrase(c)}.`),'origin'):!t.friend?n('friend','Who is your new friend?','介绍 Amy 的身份；先把四位伙伴的卡片做好。',["This is Amy. She's a student."],'friend',{blocked:Object.keys(s.passports).length<4||Object.keys(s.roles).length<4}):n('teacherIntro','Who is your teacher?','给 Mr Jones 放好 teacher 身份牌，再介绍老师。',["This is Mr Jones. He's a teacher."],'teacherIntro',{blocked:s.roles.jones!=='teacher'});
 case 'l2':return !t.father?n('father',"Who's that man?",'拍到 father 后，介绍 Leo 的爸爸。',["He's my father."],'family',{expected:'father',blocked:!s.familyFound.includes('father')}):!t.mother?n('mother',"Who's that woman?",'拍到 mother 后，介绍 Leo 的妈妈。',["She's my mother."],'family',{expected:'mother',blocked:!s.familyFound.includes('mother')}):!t.familyYes?n('familyYes','Is she your mother?','现在指的是 mother，她是 Leo 的妈妈吗？',['Yes, she is.'],'familyYes'):n('familyNo','Is he your father?','现在指的是 grandfather，他是 Leo 的爸爸吗？',["No, he isn't."],'familyNo',{blocked:!s.familyFound.includes('grandfather')});
 case 'l3':return !t.tall?n('tall','Look at that giraffe!','观察到 tall 特征，再形容长颈鹿。',["It's so tall."],'trait',{blocked:!s.observations.includes('tall')}):n('nose','Look at the elephant!','完成特征拼图，再介绍大象的鼻子。',['It has a long nose.'],'feature',{blocked:s.features.length<5});
 case 'lr1':{const i=s.gates.length,k=['gateOrigin','gateFamily','gateAnimal'][Math.min(i,2)];return i===0?n(k,'Where are you from?','先说英语，再走到迎新桥盖章。',[`I'm from ${countryPhrase(profile.country)}.`],'origin'):i===1?n(k,"Who's that man?",'介绍爸爸，再走到家庭桥盖章。',["He's my father."],'family',{expected:'father'}):n(k,'Look at the elephant!','介绍大象的鼻子，再走到动物桥盖章。',['It has a long nose.'],'feature');}
 case 'l4':{const toy=TOYS.find(o=>!t[`where-${o.word}`]);if(toy)return n(`where-${toy.word}`,`Where is my ${toy.word}?`,'先搜寻这个玩具，再告诉伙伴它原来在哪里。',[`It's ${toy.place}.`],'location',{expected:toy.place,blocked:!s.toysFound.includes(toy.word)});const blocked=TOYS.some(o=>s.toysPlaced[o.word]!==o.destination);return !t.toyYes?n('toyYes','Is the cap in the box?','把五件玩具收拾好后，确认帽子的位置。',['Yes, it is.'],'toyYes',{blocked}):n('toyNo','Is the car under the chair?','小车已收进盒子，现在还在椅子下面吗？',["No, it isn't."],'toyNo',{blocked});}
 case 'l5':return !t.taste?n('taste','Do you like pears?','喜欢或不喜欢都可以，真实表达你的选择。',['Yes, I do.',"No, I don't."],'taste'):!t.like?n('like','What fruit do you like?','说出自己喜欢的水果，角色会记住。',FRUITS.map(f=>`I like ${plural(f)}.`),'like'):n('request','What would you like?','用英语要水果；伙伴会把你选的水果送到场景里。',FRUITS.map(f=>`Can I have some ${plural(f)}?`),'request');
 case 'l6':return !t.seeKites?n('seeKites','How many kites do you see?','标记所有风筝；小黑鸟不是风筝。',['I see twelve.'],'number',{expected:12,prefix:'see',blocked:s.kites.length!==12}):!t.haveCrayons?n('haveCrayons','How many crayons do you have?','先收集全部蜡笔，再报告数量。',['I have sixteen.'],'number',{expected:16,prefix:'have',blocked:s.crayons.length!==16}):n(`launch-${s.launchTarget}`,'How many kites do you have?','选择数量目标，逐只放飞；实物数量和英语要一致。',[`I have ${COUNT_WORDS[s.launchTarget]} kites.`],'number',{expected:s.launchTarget,prefix:'have',blocked:s.launched!==s.launchTarget});
 case 'lr2':if(s.board.pending){const d=boardChallenge(s);return n(`board-${s.board.turn}`,d.npc,'说对这一轮英语，棋子才会移动，水果奖励也会到账。',d.examples,d.mode,{expected:d.expected,prefix:d.prefix,board:true});}return n('final','How many grapes do you have?',s.board.pos===20?'集齐奖励后，把葡萄数量告诉伙伴。':'先掷骰子，完成遇到的英语挑战。',['I have twenty grapes.'],'number',{expected:20,prefix:'have',blocked:s.board.pos!==20||s.board.bananas<13||s.board.grapes<20});
 }
}
export function interpretLowerSpeech(raw,node){
 const text=String(raw||'').toLowerCase().replace(/[’‘]/g,"'").replace(/[.,!?]/g,' ').replace(/\s+/g,' ').trim();
 const ok=(value,reply='Great! Let’s keep exploring!')=>({ok:true,value,reply});
 if(node.blocked)return {ok:false,reason:'先完成场景里的探索或操作，再用英语报告你的发现。'};
 switch(node.mode){
 case 'origin':{const c=COUNTRIES.find(c=>new RegExp(`\\b${c.toLowerCase()}\\b`).test(text));if(c&&/\bi(?:'m| am) from\b/.test(text))return ok(c,`Welcome! You're from ${countryPhrase(c)}.`);break;}
 case 'friend':if(/this is amy/.test(text)&&/she(?:'s| is) (?:a )?(?:student|pupil)/.test(text))return ok('student','Nice to meet you, Amy!');break;
 case 'teacherIntro':if(/this is (?:mr )?jones/.test(text)&&/he(?:'s| is) (?:a )?teacher/.test(text))return ok('teacher','Hello, Mr Jones!');break;
 case 'family':{const aliases=node.expected==='father'?'father|dad':'mother|mum|mom';const p=node.expected==='father'?'he':'she';if(new RegExp(`\\b${p}(?:'s| is) my (?:${aliases})\\b`).test(text))return ok(node.expected,'What a lovely family!');break;}
 case 'familyYes':if(/\byes she is\b/.test(text))return ok('yes','Yes! She is your mother.');break;
 case 'familyNo':if(/\bno he (?:isn't|is not)\b/.test(text))return ok('no',"He's your grandfather.");break;
 case 'trait':if(/\bit(?:'s| is) (?:so )?tall\b/.test(text))return ok('tall','Yes! The giraffe is tall.');break;
 case 'feature':if(/\bit has (?:a )?long nose\b/.test(text))return ok('long nose','Yes! It has a long nose.');break;
 case 'location':if(/\bit(?:'s| is)\b/.test(text)&&text.includes(node.expected))return ok(node.expected,`Yes! It's ${node.expected}.`);break;
 case 'toyYes':if(/\byes it is\b/.test(text))return ok('yes','Your cap is in the box.');break;
 case 'toyNo':if(/\bno it (?:isn't|is not)\b/.test(text))return ok('no','Your car is in the box.');break;
 case 'taste':if(/\byes i do\b/.test(text))return ok('yes','Have some fruit!');if(/\bno i (?:don't|do not)\b/.test(text))return ok('no','Okay! Choose another fruit.');break;
 case 'like':case 'request':{const fruit=FRUITS.find(f=>new RegExp(`\\b(?:${f}|${plural(f)})\\b`).test(text));if(fruit&&(node.mode==='like'?/\bi like\b/.test(text)&&!/don't|do not/.test(text):/\bcan i have (?:some )?/.test(text)))return ok(fruit,node.mode==='like'?`You like ${plural(fruit)}!`:`Here you are! Have some ${plural(fruit)}.`);break;}
 case 'number':{const numbers=COUNT_WORDS.map((w,i)=>new RegExp(`\\b${w}\\b`).test(text)?i:-1).filter(i=>i>=0);const digits=[...text.matchAll(/\b\d+\b/g)].map(m=>Number(m[0]));const values=[...numbers,...digits];if(new RegExp(`\\bi ${node.prefix}\\b`).test(text)&&values.length===1&&values[0]===node.expected)return ok(node.expected,`Yes! ${COUNT_WORDS[node.expected]}!`);break;}
 }
 return {ok:false,reason:node.mode==='number'?'数量或句型不对。再数一数，用 I see / I have 加上正确数量。':'伙伴还没听懂，看看说法再试试；位置、身份要和场景一致。'};
}
export const LOWER_AUDIO=[...COUNTRIES.map(c=>`I'm from ${countryPhrase(c)}.`),...COUNTRIES.map(c=>`Welcome! You're from ${countryPhrase(c)}.`),...FEATURES,...PLACES,...PLACES.map(p=>`It's ${p}.`),...PLACES.map(p=>`Yes! It's ${p}.`),...TOYS.map(t=>`Where is my ${t.word}?`),'What a lovely family!','Yes! She is your mother.','Yes! The giraffe is tall.','Yes! It has a long nose.','Your cap is in the box.','Have some fruit!','Okay! Choose another fruit.','Great! Let’s keep exploring!','Nice to meet you, Amy!','The black one is a bird!',...FRUITS.flatMap(f=>[plural(f),`I like ${plural(f)}.`,`Can I have some ${plural(f)}?`,`You like ${plural(f)}!`,`Here you are! Have some ${plural(f)}.`]),...COUNT_WORDS.flatMap(w=>[`I see ${w}.`,`I have ${w}.`,`I have ${w} kites.`,`Yes! ${w}!`]),'I see thirteen bananas.','I have twenty grapes.','family','on','in','under','student','teacher'];
