export const G6_BOOKS=['grade6upper','grade6lower'];
const say=(q,a)=>({q,answers:Array.isArray(a)?a:[a]});
const slot=(name,answer,choices)=>({name,answer,choices:choices||[answer]});
const task=(title,mode,sprite,clue,operation,reports)=>({title,mode,sprite,clue,...operation,reports});
const destinations=['science museum','post office','bookstore','cinema','hospital','supermarket'];
export const CITY=destinations.map((word,i)=>({word,xy:[[1,1],[3,1],[0,1],[2,1],[0,3],[3,3]][i]}));
const paths=[['straight','straight'],['straight','right','straight','left'],['left','right','straight'],['right','left','straight'],['left'],['right','straight']];
const route=destinations.map((w,i)=>task(w,'route',w,`把明信片送到 ${w}。路标：${paths[i].join(' → ')}。转向按钮会转身并前进一步。`,{path:paths[i],target:CITY[i].xy,slots:[slot('delivery','postcard',['postcard','word book'])]},[say('How can I get there?',paths[i].map(x=>x==='straight'?'Go straight.':`Turn ${x}.`).join(' ')),say('Where are you going?',`I am going to the ${w}.`)]));
const vehicles=['on foot','bus','plane','taxi','ship','subway','train'];
const transit=vehicles.map(w=>task(w,'match',w==='on foot'?'g6-running shoes':w,`这次用 ${w} 去学校；为旅程配上正确卡。`,{slots:[slot('travel',w,vehicles)]},[say('How do you come to school?',`I come ${w==='on foot'?'on foot':'by '+w}.`)]));
transit.push(task('traffic lights','sequence','traffic lights','红灯停止 → 黄灯减速并停止 → 绿灯通行。点击动作让角色安全通过三轮信号。',{sequence:['stop','slow down and stop','go'],buttons:['stop','slow down and stop','go']},[say('What must we do at a red light?',"Don't go at the red light."),say('What must we do at a yellow light?','Slow down and stop at a yellow light.')]));
transit.push(task('helmet','pack','helmet','骑自行车需要戴头盔；把头盔装入装备包。',{slots:[slot('equipment','helmet',['helmet','hat','life jacket'])]},[say('What must you do?','I must wear a helmet.')]));
transit.push(task('ferry','pack','ship','坐渡船去学校：带上 life jacket。雪地 sled 是教材中的另一种交通方式。',{slots:[slot('equipment','life jacket',['life jacket','helmet','sled'])]},[say('How do they go to school?','They go to school by ferry.')]));
const futurePlans=[
 ['visit my grandparents','tomorrow','house',['postcard']],['see a film','tonight','cinema',['postcard']],['take a trip','next week','park',['water bottle','map']],['have an art lesson','tomorrow','school',['crayon','pencil']],['buy books','this afternoon','bookstore',['dictionary','comic book','word book']]
];
const plans=futurePlans.map(([a,time,place,items])=>task(a,'pack',place,`行程 ${time} · ${place}；准备 ${items.join(' + ')}。电影院用 postcard 作为岛屿兑换券。`,{slots:[slot('time',time,['tomorrow','tonight','next week','this afternoon']),slot('place',place,['house','cinema','park','school','bookstore']),slot('bag',items, [...new Set([...items,'water bottle','comic book'])])]},[say('What are you going to do?',`I am going to ${a}.`),say('Where are you going?',`I am going to the ${place}.`),say('When are you going?',`I am going ${time}.`)]));
const hobbies=['reading stories','dancing','singing','playing football','doing kung fu','doing word puzzles','going hiking'];
const penpals=[['Peter',['reading stories','dancing'],'He likes reading stories and dancing.'],['Amy',['singing','doing kung fu'],'She likes singing and doing kung fu.'],['Mike',['playing football'],'He likes playing football.'],['John',['doing word puzzles','going hiking'],'He likes doing word puzzles and going hiking.']].map(([who,h,report],i)=>task(who,'pack',i===1?'Amy':i===2?'Mike':'John',`${who} 的兴趣档案：${h.join(' + ')}。John 住在 Canberra，学习中文。为他拼出 HIKE。`,{slots:[slot('hobbies',h,hobbies)],...(i===3?{sequence:['H','I','K','E'],buttons:['H','E','I','K']}: {})},[say("What are your pen pal's hobbies?",report),...(i===3?[say('Does John live in Sydney?','No, he does not. He lives in Canberra.'),say('Does he study Chinese?','Yes, he does.')]:[])]));
const jobData=[['factory worker','He','factory','bus'],['postman','He','post office','bike'],['businessman','He','office','car'],['police officer','She','police station','car'],['fisherman','He','sea','bike'],['scientist','She','university','subway'],['pilot','She','airport','car'],['coach','She','gym','on foot']];
const jobs=jobData.map(([job,p,work,transport])=>task(job,'match','g6-'+job,`职业档案：${job}；工作地点 ${work}；通勤 ${transport}。`,{slots:[slot('job',job,jobData.map(x=>x[0])),slot('work',work,jobData.map(x=>x[2])),slot('travel',transport,['bus','bike','car','subway','on foot'])]},[say(`What does ${p.toLowerCase()} do?`,`${p} is a ${job}.`),say(`Where does ${p.toLowerCase()} work?`,`${p} works ${work==='sea'?'at sea':'in the '+work}.`),say(`How does ${p.toLowerCase()} go to work?`,`${p} goes to work ${transport==='on foot'?'on foot':'by '+transport}.`)]));
const feelings=[
 task('angry','sequence','g6-angry fox','小狐狸生气了。先选深呼吸，再按 1–10 数数；完成后他的表情会变化。',{slots:[slot('help','take a deep breath',['take a deep breath','see a doctor','wear warm clothes'])],sequence:Array.from({length:10},(_,i)=>String(i+1)),buttons:Array.from({length:10},(_,i)=>String(i+1))},[say('How does he feel?','He is angry.'),say('What should he do?','He should take a deep breath and count to ten.')]),
 ...[['afraid','stay with a friend','g6-afraid fox'],['sad','read a letter','g6-sad fox'],['worried','make a plan','g6-worried fox'],['happy','share a gift','g6-happy fox'],['ill','see a doctor','g6-worried fox'],['cold','wear warm clothes','g6-sad fox'],['weak','do more exercise','g6-sad fox']].map(([feel,help,sprite])=>task(feel,'match',sprite,`小狐狸的状态：${feel}；帮助方案：${help}。选对帮助卡，走近确认后表情变成 happy。`,{slots:[slot('help',help,[help,'count to ten','take a deep breath','see a doctor'].filter((x,i,a)=>a.indexOf(x)===i))]},[say('How does he feel?',`He is ${feel}.`),say('What should he do?',`He should ${help}.`)]))
];
const comparison=[
 ['taller','Amy','Mike',165,160,'cm','Amy is taller than Mike.','Amy is one point six five metres tall.'],['shorter','Mike','Amy',160,165,'cm','Mike is shorter than Amy.'],['older','Grandfather','Father',70,40,'years','Grandfather is older than Father.'],['younger','Father','Grandfather',40,70,'years','Father is younger than Grandfather.'],['longer','ruler A','ruler B',20,15,'cm','Ruler A is longer than ruler B.'],['thinner','English book','storybook',12,20,'mm','The English book is thinner than the storybook.'],['heavier','bag A','bag B',6,4,'kg','Bag A is heavier than bag B.'],['bigger','dinosaur A','dinosaur B',130,60,'cm','Dinosaur A is bigger than dinosaur B.'],['smaller','dinosaur B','dinosaur A',60,130,'cm','Dinosaur B is smaller than dinosaur A.'],['stronger','Robin','Fox',5,2,'boxes','Robin is stronger than Fox.']
];
const measure=comparison.map(([word,a,b,v,bv,unit,report,extra])=>task(word,'measure',a.startsWith('dinosaur')?'dinosaur':a==='Robin'?'Robin':a.includes('book')?'English book':a.includes('bag')?'bag':a.includes('ruler')?'ruler':a==='Grandfather'?'grandfather':a==='Father'?'father':'Amy',`虚构展览数据：${a} ${v} ${unit}；${b} ${bv} ${unit}。按数据选择工具，调读数，再选比较级。`,{measure:{a,b,v,bv,unit},slots:[slot('tool',unit==='kg'?'weighing scale':unit==='years'?'calendar':unit==='boxes'?'box':'measuring tape',['measuring tape','weighing scale','calendar','box']),slot('comparison',word,comparison.map(x=>x[0]))]},[say('Compare them, please.',report),...(extra?[say('How tall is Amy?',[extra,'Amy is 1.65 metres tall.'])]:[])]));
const memories=[['cleaned my room','washed my clothes','broom','shirt'],['stayed at home','watched TV','house','TV'],['had a cold','slept','doctor','bed'],['read a book','saw a film','book','cinema']];
const memory=memories.map(([a,b,sa,sb])=>task(a,'memory',sa,`周末照片被藏起来了。走近两个地点发现照片，再按 ${a} → ${b} 排进相册。`,{collect:[a,b],collectSprites:[sa,sb],sequence:[a,b],buttons:[b,a]},[say('What did you do last weekend?',`I ${a} and ${b}.`),say('How was your weekend?',a==='had a cold'?'It was not good.':'It was good.'),...(a==='had a cold'?[say('Did you see a film?',"No, I did not. I stayed at home and slept.")]:[])]));
const holidays=[['Turpan','train',['went camping','rode a horse'],['camping tent','g6-horse']],['the countryside','bike',['went fishing','rode a bike'],['fishing rod','bike']],['Sanya','plane',['ate fresh food','took pictures','bought gifts'],['apple','camera','present']]];
const travel=holidays.map(([place,vehicle,actions,sprites])=>task(place,'memory',place==='Sanya'?'plane':'camping tent',`旅行档案：${place}，交通 ${vehicle}。走近收集 ${actions.join(' → ')} 的照片，按经历顺序装相册。`,{collect:actions,collectSprites:sprites,sequence:actions,buttons:[...actions].reverse(),slots:[slot('travel',vehicle,['plane','bike','train']),slot('place',place,holidays.map(x=>x[0]))]},[say('Where did you go?',`I went to ${place}.`),say('How did you go there?',`I went there by ${vehicle}.`),say('What did you do?',`I ${actions.join(' and ')}.`)]));
travel.push(task('hurt my foot','sequence','doctor','骑车摔倒的旅行回忆：fell off my bike → hurt my foot → saw a doctor。现在已经好转。',{sequence:['fell off my bike','hurt my foot','saw a doctor'],buttons:['saw a doctor','fell off my bike','hurt my foot']},[say('What happened?','I fell off my bike and hurt my foot.'),say('Are you all right?',"I am OK now.")]));
const changes=['library','dining hall','gym','grass','computers'].map(w=>task(w,'change',w==='computers'?'computer':w,`时光机：以前没有 ${w}，现在有。分别打开 before / now；在 now 画面把新设施放入学校。`,{slots:[slot('school',w,[w,'calendar','book'])],views:['before','now']},[say('What was your school like?',w==='computers'?'There were no computers in my old school.':`There was no ${w} in my old school.`),say('What is it like now?',w==='computers'?'There are computers now.':`There is ${w==='grass'?'':'a '}${w} now.`)]));
changes.push(task('cycling','change','bike','before：个子小，不会骑车。now：可以骑车、打羽毛球和滑冰。两次切换后修好自行车。',{slots:[slot('school','bike',['bike','badminton','ice-skate'])],views:['before','now']},[say('How have you changed?',"Before, I could not ride my bike well. Now I go cycling every day."),say('What can you do now?','I can play badminton and ice-skate.')]));
const farm=[['a',['pear','jacket'],['pear','jacket','egg']],['an',['egg','orange','umbrella'],['egg','orange','umbrella','pear']],['some',['apples','horses','tomatoes'],['apples','horses','tomatoes','egg']]].map(([article,items,choices])=>task(article,'pack','basket',`Day 1 农场词汇分类：把 ${items.join(' + ')} 放到 ${article} 篮，注意数量与元音开头。`,{slots:[slot(article,items,choices)]},[say('What can you see?',`I can see ${items.map(x=>article+' '+x).join(' and ')}.`)]));
const market=[['apples',3],['jacket',5],['umbrella',4]].map(([word,price],i)=>task(word,'shop',word,`Day 2 虚构集市：${word} 花 ${price} 游戏币。预算共 12；选商品装购物袋，可取回恢复原价。`,{price,slots:[slot('cart',word,['apples','jacket','umbrella'])]},[say('What are you going to buy?',`I am going to buy ${word==='apples'?'some':word==='umbrella'?'an':'a'} ${word}.`),...(i===1?[say('What is Bill like?','Bill is short and heavy.')]:i===2?[say('What is Mrs Booth like?','She is tall and thin. She has long hair.')]:[])]));
const dailyFarm=[['He goes fishing.','He is fishing.','fishing rod'],['She does the cleaning.','She is cleaning.','broom'],['Bill plays ping-pong.','Bill is playing ping-pong.','ping-pong']].map(([normal,now,sprite])=>task(normal,'change',sprite,`Day 3 生活节奏：every day（经常）与 now（正在）。看两个画面再配对句卡。`,{views:['before','now'],slots:[slot('every day',normal,[normal,now]),slot('now',now,[now,normal])]},[say('What happens every day?',normal),say('What is happening now?',now)]));
const day4=[task('farm diary','memory','photo','Day 4 按 Mike 的昨天排列日记：had breakfast → cleaned my room → went fishing。',{collect:['had breakfast','cleaned my room','went fishing'],collectSprites:['breakfast','broom','fishing rod'],sequence:['had breakfast','cleaned my room','went fishing'],buttons:['went fishing','had breakfast','cleaned my room']},[say('What did Mike do yesterday?','He had breakfast, cleaned his room and went fishing.')]),task('animal sizes','sequence','whale','把动物从小到大排队：tiger → elephant → whale。鲸鱼最大，老虎最小。',{sequence:['tiger','elephant','whale'],buttons:['whale','tiger','elephant']},[say('Compare the animals.','The tiger is smaller than the elephant. The whale is the biggest.')])];
const day5=[['favourite day','Monday',['Monday','Friday'],'Monday is my favourite day.'],['first class','maths',['English','maths'],'I have maths first on Mondays.'],['favourite class','PE',['English','PE'],'PE is my favourite class.'],['favourite sport','football',['basketball','football'],'Football is my favourite sport.']].map(([label,answer,choices,report])=>task(label,'match',label==='favourite sport'?'ball':'school',`Day 5 修正 Bill 写错的 PPT。Mike 的正确资料：${answer}。扮演 Mike 选正确卡并介绍。`,{slots:[slot(label,answer,choices)]},[say('Tell us about your school.',report)]));
const day6=[task('Bill at five','poster','schoolboy','Day 6 海报：五岁 Bill 喜欢 candy 和 basketball，不喜欢 skip rope。',{views:['before','now'],slots:[slot('age five',['candy','basketball'],['candy','basketball','skip rope'])]},[say('What did Bill like at five?','He liked candy and basketball.')]),task('Bill at twelve','poster','schoolboy','十二岁 Bill 喜欢 music 和 storybooks，不喜欢 swimming。',{slots:[slot('age twelve',['music','storybooks'],['music','storybooks','swimming'])]},[say('What does Bill like now?','He likes music and storybooks.')]),task('Bill in the future','poster','car','未来 Bill 开红车、戴黄帽。选好颜色完成海报，使用 will。',{slots:[slot('car','red',['red','blue','yellow']),slot('hat','yellow',['red','blue','yellow'])]},[say('What will Bill do?','He will drive a red car and wear a yellow hat.')])];
const invite=[task('farewell invitation','pack','postcard','Day 7 毕业聚会：Friday / three p.m. / music room。你可以选择 sing、dance、draw pictures 或 play games 来回复邀请。',{slots:[slot('day','Friday',['Thursday','Friday']),slot('time','three p.m.',['two p.m.','three p.m.']),slot('place','music room',['library','music room']),slot('activity','*',['sing','dance','draw pictures','play games']),slot('envelope','postcard',['postcard','dictionary'])]},[say('When and where is the party?','It is on Friday at three p.m. in the music room.'),say('What will you do at the party?',['I will sing.','I will dance.','I will draw pictures.','I will play games.'])])];
const party=[task('party table','pack','cake','Day 8 摆聚会餐桌：把 cake、juice、plates 放到 table。',{slots:[slot('table',['cake','juice','plates'],['cake','juice','plates','dictionary'])]},[say('What is on the table?','There is cake and juice. There are plates.')]),task('party show','sequence','dancing','舞台演出：clap → dance → bow，按顺序操作。',{sequence:['clap','dance','bow'],buttons:['bow','clap','dance']},[say('Say goodbye to your friends.',['Keep in touch. Take care.','Good luck! Write soon.','Have a good trip!'])])];
const stage=(name,pages,tasks)=>({name,pages,tasks});
export const G6_STAGES={g6u1:[stage('小镇导航','2–11',route)],g6u2:[stage('交通探险','12–21',transit)],g6u3:[stage('周末计划','22–31',plans)],g6ur1:[stage('送信','32–33',route.slice(0,2)),stage('乘车','34',transit.slice(-3,-1)),stage('出发计划','35',plans.slice(0,1))],g6u4:[stage('笔友俱乐部','36–45',penpals)],g6u5:[stage('职业岛','46–55',jobs)],g6u6:[stage('情绪救援','56–65',feelings)],g6ur2:[stage('笔友来信','66',penpals.slice(3)),stage('工作调查','67–68',jobs.slice(4,6)),stage('帮助朋友','69',feelings.slice(0,1))],g6l1:[stage('测量博物馆','2–11',measure)],g6l2:[stage('周末记忆相册','12–21',memory)],g6l3:[stage('旅行搜集','22–31',travel)],g6l4:[stage('学校时光机','32–41',changes)],g6lr:[stage('Day 1 · A beautiful farm','42',farm),stage('Day 2 · Farmers market','43',market),stage('Day 3 · Life on the farm','44',dailyFarm),stage('Day 4 · Diary and animals','45',day4),stage('Day 5 · Mike’s PPT','46',day5),stage('Day 6 · Bill’s poster','47',day6),stage('Day 7 · Invitation','48',invite),stage('Day 8 · Farewell party','49–51',party)]};
const upperWords=[
 ['science museum','post office','bookstore','cinema','hospital','crossing','turn','left','straight','right','ask','sir','interesting','Italian','restaurant','pizza','street','get','BDS','gave','feature','follow','far','tell'],
 ['on foot','by','bus','plane','taxi','ship','subway','train','slow down','stop','Mrs','early','helmet','must','wear','attention','pay attention to','traffic lights','Munich','Germany','Alaska','sled','fast','ferry','Papa Westray','Scotland'],
 ['visit','film','see a film','trip','take a trip','supermarket','evening','tonight','tomorrow','next week','dictionary','comic book','word book','postcard','lesson','space','travel','half','price','Mid-Autumn Festival','together','get together','mooncake','poem','moon'],
 ['dancing','singing','reading stories','playing football','doing kung fu','cooks Chinese food','studies Chinese','does word puzzles','goes hiking','pen pal','hobby','jasmine','idea','Canberra','amazing','shall','goal','join','club','share'],
 ['factory worker','postman','businessman','police officer','fisherman','scientist','pilot','coach','country','head teacher','sea','stay','university','gym','if','reporter','use','type','quickly','secretary'],
 ['angry','afraid','sad','worried','happy','see a doctor','wear warm clothes','do more exercise','take a deep breath','count to ten','chase','mice','bad','hurt','ill','wrong','should','feel','well','sit','grass','hear','ant','worry','stuck','mud','pull','everyone']
];
const lowerWords=[comparison.map(x=>x[0]).concat(['dinosaur','hall','metre','than','both','kilogram','countryside','lower','shadow','smarter','become']),['cleaned','stayed','washed','watched','had a cold','slept','read','saw','last','yesterday','before','drank','show','magazine','better','faster','hotel','fixed','broken','lamp','loud','enjoy'],['went camping','went fishing','rode a horse','rode a bike','hurt my foot','ate fresh food','took pictures','bought gifts','fell','off','Labour Day','mule','Turpan','could','till','beach','basket','part','licked','laughed'],['dining hall','grass','gym','ago','cycling','go cycling','ice-skate','badminton','star','easy','look up','Internet','different','active','race','nothing','thought','felt','cheetah','trip','woke','dream']];
const phonics=[
 {'Robin has BDS.':'降调','Follow me, please!':'升调','Is it far?':'升调','Where is the restaurant?':'降调'},
 {'come and have a look':'连读','pictures of':'连读','stop at a red light':'连读'},
 {lesson:'首音节重读',dinner:'首音节重读',tonight:'第二音节重读',tomorrow:'第二音节重读'},
 {'We can share.':'句子重音','I like dancing.':'句子重音','He lives on a farm.':'句子重音',"What are Peter’s hobbies?":'句子重音'},
 {'He is good at football, ping-pong and basketball.':'停顿','If you like sports, you can be a coach, a sports reporter, or a PE teacher.':'停顿'},
 {'next day':'不完全爆破',"can’t go":'不完全爆破','count to':'不完全爆破',"don’t be":'不完全爆破'},
 {taller:'直接加 er',longer:'直接加 er',thinner:'双写加 er',bigger:'双写加 er',heavier:'y 变 i 加 er'},
 {cleaned:'规则过去式',washed:'规则过去式',stayed:'规则过去式',watched:'规则过去式',slept:'不规则过去式',read:'不规则过去式',saw:'不规则过去式'},
 {went:'不规则过去式',rode:'不规则过去式',hurt:'不规则过去式',ate:'不规则过去式',took:'不规则过去式',bought:'不规则过去式'},
 {was:'单数过去',were:'复数过去',could:'can 的过去',thought:'不规则过去式',felt:'不规则过去式',woke:'不规则过去式'}
];
export const G6_REVIEW_PATTERNS={bread:'br',chair:'ch',clean:'cl',green:'gr',sing:'ng',pink:'nk',plane:'pl',quick:'qu',shoe:'sh',thin:'th /θ/',this:'th /ð/',what:'wh /w/',who:'wh /h/',cat:'短 a',bed:'短 e',pig:'短 i',dog:'短 o',bus:'短 u',cake:'a-e',bike:'i-e',home:'o-e',cute:'u-e',we:'-e',tiger:'er',bird:'ir',nurse:'ur',car:'ar',ball:'al',horse:'or',world:'w-or',happy:'-y',feet:'ee',tea:'ea',cow:'ow /aʊ/',snow:'ow /əʊ/',book:'oo /ʊ/',food:'oo /uː/',house:'ou',rain:'ai',say:'ay',friend:'fr'};
const phonicNotes=['语调箭头表示句末升降，不评分你的音高。','come‿and / pictures‿of / stop‿at：连起来读。','LESSon、DINner；toNIGHT、toMORrow。','重读 share；like / dancing；lives / farm；What / Peter’s / hobbies。','football / ping-pong / basketball 之间停顿；职业列表也分组。','相邻辅音间 /t/ 可不完全爆破；不要在 next day 中额外加元音。','比较级先看词形：tall→taller，thin→thinner，heavy→heavier。','规则与不规则过去式；read 的过去式读 /red/，听完整过去时句子。','go→went；ride→rode；hurt→hurt；eat→ate；take→took；buy→bought。','is/am→was，are→were，can→could；then 与 now 对比。'];
const meta=[['g6u1',1,'How can I get there?','小镇导航','2–11',0,'9','science museum'],['g6u2',2,'Ways to go to school','交通探险','12–21',1,'19','traffic lights'],['g6u3',3,'My weekend plan','计划打包','22–31',2,'29','dictionary'],['g6ur1',0,'Recycle 1','小镇出发日','32–35',0,'9、19、29','postcard'],['g6u4',4,'I have a pen pal','笔友俱乐部','36–45',3,'43','comic book'],['g6u5',5,'What does he do?','职业岛','46–55',4,'53','g6-scientist'],['g6u6',6,'How do you feel?','情绪救援','56–65',5,'63','g6-happy fox'],['g6ur2',0,'Recycle 2','岛屿互助节','66–69',3,'43、53、63','present'],['g6l1',1,'How tall are you?','测量博物馆','2–11',6,'10','dinosaur'],['g6l2',2,'Last weekend','周末记忆相册','12–21',7,'20、69','photo'],['g6l3',3,'Where did you go?','旅行搜集','22–31',8,'30、69','camera'],['g6l4',4,'Then and now','学校时光机','32–41',9,'40、69','gym'],['g6lr',0,'Mike’s happy days','八天毕业旅行','42–51',10,'49、70–71','present']];
export const GRADE6_CHAPTERS=meta.map(([id,u,title,name,pages,pi,phonicsPages,rewardSprite])=>{
 let patterns=pi===10?G6_REVIEW_PATTERNS:phonics[pi];
 if(id==='g6ur1')patterns=Object.assign({},...phonics.slice(0,3));if(id==='g6ur2')patterns=Object.assign({},...phonics.slice(3,6));
 const stages=G6_STAGES[id];return {id,book:id.startsWith('g6u')?'grade6upper':'grade6lower',unit:u?'Unit '+u:id==='g6lr'?'Recycle':title,title,name,pages,kind:'g6-'+stages[0].tasks[0].mode,letters:'',goals:stages.length>1?['完成前段冒险','完成中段冒险','完成全部操作与对话']:['完成第一组任务','完成第二组任务','完成全部操作与对话'],words:u?(id.startsWith('g6u')?upperWords[u-1]:lowerWords[u-1]):[...new Set(stages.flatMap(s=>s.tasks.map(t=>t.title)))],expressions:stages.flatMap(s=>s.tasks.flatMap(t=>t.reports.flatMap(r=>r.answers))),phonics:Object.keys(patterns),patterns,phonicsPages,phonicNote:phonicNotes[pi]||'复习附录发音组合，点击示范再选规律。',rewardSprite,reward:name+'纪念章',hint:'操作场景 → 开口报告 → 走近确认。'+(stages.length>1?`本关 ${stages.length} 幕，可中途保存。`:'所有英语与物体都能点读。')};
});
export const g6Stage=(c,g)=>G6_STAGES[c.id][g.stage];
export const g6Task=(c,g)=>g6Stage(c,g)?.tasks[g.round];
export function g6Position(path){let x=1,y=3,d=0;for(const turn of path){d=(d+(turn==='left'?3:turn==='right'?1:0))%4;x+=[0,1,0,-1][d];y+=[-1,0,1,0][d];}return {x,y,d};}
export function g6Operation(r,g){return !!r && (!r.path||JSON.stringify(g.path)===JSON.stringify(r.path))&&(!r.sequence||g.sequence.join('|')===r.sequence.join('|'))&&(!r.collect||r.collect.every(w=>g.collected.includes(w)))&&(!r.views||r.views.every(w=>g.views.includes(w)))&&(!r.measure||g.reading===r.measure.v)&&r.slots?.every(s=>s.answer==='*'?s.choices.includes(g.slots[s.name]?.[0]):JSON.stringify([...(g.slots[s.name]||[])].sort())===JSON.stringify([...(Array.isArray(s.answer)?s.answer:[s.answer])].sort()))!==false&&g.inspected;}
export function g6Nodes(c,stage,round,g,blocked=false){const r=G6_STAGES[c.id][stage]?.tasks[round];if(!r)return [];return r.reports.map((report,i)=>({key:`g6-${stage}-${round}-${i}`,g6:true,mode:'g6',npc:report.q,help:'先完成场景操作；完整说出与结果一致的句子。可点“看说法”听示范。',examples:report.answers.filter(a=>r.title!=='farewell invitation'||i!==1||a.toLowerCase().includes((g.slots.activity?.[0]||'sing').toLowerCase())),blocked}));}
export function grade6Dialogue(c,s){const g=s.g6,r=g6Task(c,g);if(!r)return {key:'g6-end',g6:true,mode:'g6',npc:g.stage<G6_STAGES[c.id].length?'Great! This part is complete.':'Great! Your adventure is complete.',help:g.stage<G6_STAGES[c.id].length?'走近通行门进入下一幕。':'可以重玩本关或继续下一册。',examples:['Thank you!'],blocked:false};const nodes=g6Nodes(c,g.stage,g.round,g,!g6Operation(r,g));return nodes.find(n=>!s.talks[n.key])||nodes.at(-1);}
export function normalizeG6(raw){return String(raw||'').toLowerCase().replace(/[’‘]/g,"'").replace(/\b(i'm|he's|she's|it's|they're|we're)\b/g,m=>({'i\'m':'i am',"he's":'he is',"she's":'she is',"it's":'it is',"they're":'they are',"we're":'we are'}[m])).replace(/\b(don't|doesn't|didn't|can't|couldn't|isn't|aren't|weren't)\b/g,m=>({"don't":'do not',"doesn't":'does not',"didn't":'did not',"can't":'cannot',"couldn't":'could not',"isn't":'is not',"aren't":'are not',"weren't":'were not'}[m])).replace(/\bi'll\b/g,'i will').replace(/\bhe'll\b/g,'he will').replace(/\bcan not\b/g,'cannot').replace(/1\.65/g,'one point six five').replace(/\b(?:10|[0-9])\b/g,m=>['zero','one','two','three','four','five','six','seven','eight','nine','ten'][+m]).replace(/\bfavorite\b/g,'favourite').replace(/\bmeters\b/g,'metres').replace(/\b3\s*(?:p\.?\s*m\.?)\b/g,'three pm').replace(/[.,!?;:–-]/g,' ').replace(/\bp m\b/g,'pm').replace(/\s+/g,' ').trim();}
export function interpretGrade6Speech(raw,n){if(n?.blocked)return {ok:false,reason:'先完成本轮操作，再用英语报告。'};return n?.examples.some(a=>normalizeG6(a)===normalizeG6(raw))?{ok:true,value:n.key,reply:'Great! Your report matches the scene.'}:{ok:false,reason:'句子要与操作结果一致。注意比较、时间、过去式和肯定否定；可以点“看说法”再试。'};}
export const g6Sample=(c,w)=>c.book==='grade6lower'&&['read','read a book'].includes(w)?'I read a book yesterday.':w;
export function grade6Audio(){const all=Object.values(G6_STAGES).flat().filter(st=>/[a-z]/i.test(st.name)).map(st=>st.name).concat(['Great! This part is complete.','Great! Your adventure is complete.','Great! Your report matches the scene.','I read a book yesterday.','Thank you!','measurement','before','now','straight','left','right','stop','slow down and stop','go',...Object.keys(G6_REVIEW_PATTERNS)]);for(const c of GRADE6_CHAPTERS)for(const s of G6_STAGES[c.id])for(const r of s.tasks){all.push(r.title,...(r.measure?[r.measure.a,r.measure.b,...[r.measure.v,r.measure.bv].map(v=>`${v} ${{cm:'centimetres',mm:'millimetres',kg:'kilograms',years:'years',boxes:'boxes'}[r.measure.unit]}`)]:[]),...(r.buttons||[]),...(r.collect||[]),...(r.slots||[]).flatMap(s=>[s.name,...s.choices]),...r.reports.flatMap(n=>[n.q,...n.answers]));}return [...new Set(all)];}
