import {G6_STAGES,CITY,g6Stage,g6Task,g6Position,g6Operation,g6Sample} from './curriculum-grade6.js';
export const G6_CITY_SPRITES=['science museum','post office','bookstore','cinema','hospital','supermarket','crossing','traffic lights','bus','plane','taxi','subway','train','ship','sled','life jacket'];
export const G6_JOB_SPRITES=['dictionary','comic book','word book','postcard','g6-factory worker','g6-postman','g6-businessman','g6-police officer','g6-fisherman','g6-scientist','g6-pilot','g6-coach','dinosaur','measuring tape','weighing scale','g6-running shoes'];
export const G6_PAST_SPRITES=['g6-angry fox','g6-afraid fox','g6-sad fox','g6-worried fox','g6-happy fox','helmet','camping tent','fishing rod','g6-horse','camera','grass','gym','dining hall','ant','badminton','whale'];
export const G6_SPRITES=[G6_CITY_SPRITES,G6_JOB_SPRITES,G6_PAST_SPRITES];
const aliases={'on foot':'g6-running shoes',apples:'apple',horses:'g6-horse',tomatoes:'tomato',jacket:'coat',plates:'plate',basketball:'basketball station',candy:'cake',storybooks:'book',music:'microphone','skip rope':'ball',sing:'microphone',dance:'dancing','draw pictures':'picture','play games':'ball','ice-skate':'shoes',football:'ball',PE:'ball',maths:'maths book',English:'English book'};
const sprite=w=>G6_CITY_SPRITES.includes(w)||G6_JOB_SPRITES.includes(w)||G6_PAST_SPRITES.includes(w)?w:aliases[w]||({'factory worker':'g6-factory worker',postman:'g6-postman',businessman:'g6-businessman','police officer':'g6-police officer',fisherman:'g6-fisherman',scientist:'g6-scientist',pilot:'g6-pilot',coach:'g6-coach'}[w])||({'reading stories':'book',dancing:'dancing',singing:'microphone','playing football':'ball','doing kung fu':'kung fu dummy','doing word puzzles':'word book','going hiking':'g6-running shoes','take a deep breath':'g6-happy fox','see a doctor':'doctor','wear warm clothes':'coat','do more exercise':'morning exercises'}[w])||(['apple','coat','umbrella','egg','pear','tomato','basket','bag','book','water bottle','map','pencil','crayon','house','school','park','car','bike','dancing','calendar','box','present','broom','shirt','TV','bed','doctor','photo','ball','microphone','library','computer','cake','juice','plate','Amy','Mike','John'].includes(w)?w:'word book');
export function makeGrade6Scene({chapter:c,lesson:s},h,ui={}){const {object,zone,position,imageHtml,sayButton,esc}=h,g=s.g6,st=g6Stage(c,g),r=g6Task(c,g),objects=[],zones=[],actions=[];let decor='';
 const control=(action,value,label=value,active=false)=>`<button data-lower-action="${action}" data-value="${esc(value)}" class="${active?'active':''}">${esc(label)}</button>`;
 const colors={red:'#e96952',blue:'#509dbd',yellow:'#f3cd59'};
 const picture=(word,art=word)=>`<button class="pronounce-picture" data-say="${esc(word)}" aria-label="听 ${esc(word)} 的发音">${colors[word]?`<span class="g6-color-chip" style="background:${colors[word]}"></span>`:imageHtml(art)}</button>`;
 const speakable=text=>String(text).split(/([A-Za-z][A-Za-z0-9’'.,!? -]*)/g).map((part,i)=>i%2?sayButton(part.trim(),part):esc(part)).join('');
 const card=(id,x,y,w,h,label,html,extra={})=>zones.push(zone(id,x,y,w,h,label,{html,className:'g6-card',speech:label,...extra}));
 if(!r){decor+=`<div class="g6-summary">${g.stage<G6_STAGES[c.id].length?'本幕完成！走近通行门进入下一幕。':'本关已完成！点“再玩一遍”重新挑战。'}</div>`;objects.push(object('g6-reward',c.rewardSprite,470,260,240,240,{label:c.reward,speech:'Great!'}));if(st)objects.push(object('g6-next-stage','door',850,410,110,140,{label:g.stage===G6_STAGES[c.id].length-1?'通行门 · 领奖':'通行门 · 下一幕',speech:'door',action:'g6-next-stage',value:'next'}));return {objects,zones,decor,actions};}
 const ready=g6Operation(r,g);decor+=`<div class="g6-summary">${G6_STAGES[c.id].length>1?`第 ${g.stage+1}/${G6_STAGES[c.id].length} 幕 · ${/[a-z]/i.test(st.name)?sayButton(st.name):esc(st.name)} · p.${st.pages}<br>`:''}任务 ${g.round+1}/${st.tasks.length} · ${sayButton(r.title)} · ${g.inspected?speakable(r.clue):'先走近右侧人物，查看任务线索。'}</div>`;
 objects.push(object('g6-inspect',ready&&c.id==='g6u6'?'g6-happy fox':'fox',910,135,105,120,{label:g.inspected?'线索已读':'查看线索',speech:'Fox',action:'g6-inspect',value:'inspect'}));
 objects.push(object('g6-finish','cash register',910,425,110,100,{label:'确认本轮',speech:'Great!',action:'g6-finish',value:'confirm'}));
 if(r.mode==='route'){
  const p=g6Position(g.path);decor+=`<div class="g6-city">${Array.from({length:16},(_,i)=>{const x=i%4,y=Math.floor(i/4),b=CITY.find(a=>a.xy[0]===x&&a.xy[1]===y);return `<div class="g6-city-cell ${x===r.target[0]&&y===r.target[1]?'destination':''}">${b?picture(b.word)+sayButton(b.word):picture('crossing','crossing')}${p.x===x&&p.y===y?`<button class="g6-robin" data-say="Robin" aria-label="听 Robin 的发音" style="--heading:${p.d*90}deg">${imageHtml('Robin')}<b>↑</b></button>`:''}</div>`;}).join('')}</div><div class="g6-route-controls">${['left','straight','right'].map(x=>control('g6-route',x,x)).join('')}${control('g6-reset-route','reset','重走路线')}</div>`;
 }else if(r.mode==='measure'){
  const m=r.measure,scale=['cm','mm'].includes(m.unit),ha=scale?Math.max(32,75*m.v/Math.max(m.v,m.bv)):70,hb=scale?Math.max(32,75*m.bv/Math.max(m.v,m.bv)):70;card('measurement',375,245,535,220,'measurement',`<div class="g6-measure-pair"><div><div class="g6-measure-art" style="height:${ha}%">${picture(m.a,r.sprite)}</div>${sayButton(m.a)}<small>${sayButton(`${m.v} ${{cm:'centimetres',mm:'millimetres',kg:'kilograms',years:'years',boxes:'boxes'}[m.unit]}`,`${m.v} ${m.unit}`)}</small></div><div><div class="g6-measure-art" style="height:${hb}%">${picture(m.b,m.b==='Fox'?'fox':m.b==='Father'?'father':m.b==='Grandfather'?'grandfather':m.b==='Mike'?'Mike':m.b==='Amy'?'Amy':r.sprite)}</div>${sayButton(m.b)}<small>${sayButton(`${m.bv} ${{cm:'centimetres',mm:'millimetres',kg:'kilograms',years:'years',boxes:'boxes'}[m.unit]}`,`${m.bv} ${m.unit}`)}</small></div></div><div class="g6-reading">读数 ${sayButton(`${g.reading} ${{cm:'centimetres',mm:'millimetres',kg:'kilograms',years:'years',boxes:'boxes'}[m.unit]}`,`${g.reading} ${m.unit}`)} ${[-10,-1,1,10].map(x=>control('g6-reading',String(x),x>0?'+'+x:String(x))).join('')}</div>`);
 }else if(r.mode==='memory'){
  r.collect.forEach((w,i)=>objects.push(object('g6-photo-'+i,r.collectSprites[i],170+i*(r.slots?.length?(r.collect.length===2?300:205):(r.collect.length===2?420:245)),235,ui.compact?155:135,165,{label:g.collected.includes(w)?w:'发现照片',speech:g6Sample(c,w),action:'g6-collect',value:w})));
 }else{
  const daily=r.mode==='change'&&r.title.endsWith('.'),art=ready&&c.id==='g6u6'?'g6-happy fox':r.sprite,display=daily?r.reports[g.view==='before'?0:1].answers[0]:r.title;card('g6-exhibit',235,r.sequence?215:245,220,r.sequence?170:200,r.title,`${r.mode==='change'&&!daily&&r.views&&(g.view==='before'||!g.slots.school?.length)?`<div class="g6-empty">${g.view==='before'?'过去的空地':'准备建设'}</div>`:picture(display,art)}${sayButton(display)}`);
 }
 if(r.views){decor+=`<div class="g6-view-controls">${r.views.map(v=>control('g6-view',v,r.title.endsWith('.')&&v==='before'?'every day':v,g.view===v)).join('')}</div>`;}
 if(r.sequence){const current=r.sequence[Math.min(g.sequence.length,r.sequence.length-1)];decor+=`<div class="g6-sequence">${r.mode==='sequence'&&r.title==='traffic lights'?`<span class="g6-signal ${['red','yellow','green'][Math.min(g.sequence.length,2)]}"></span>`:''}<div>${r.sequence.map((w,i)=>sayButton(g6Sample(c,w),`${i<g.sequence.length?'✓ ':''}${w}`)).join(' → ')}</div><div>${r.buttons.map(w=>control('g6-sequence',w,w,g.sequence.includes(w))).join('')}</div><small>${g.sequence.length}/${r.sequence.length}${r.title==='traffic lights'?' · 当前 '+['red','yellow','green'][Math.min(g.sequence.length,2)]:''}</small></div>`;}
 const slots=r.slots||[],selected=slots[ui.slotPage||0]||slots[0];
 if(slots.length){const centered=['route','memory','measure'].includes(r.mode);const x=centered?760:570,y=centered?280:ui.compact&&slots.length>3?280:r.sequence?215:240,w=centered?215:380,height=centered?180:ui.compact&&slots.length>3?180:r.sequence?170:210;
  decor+=`<div class="g6-slot-tabs ${centered?'g6-side-tabs':''}">${slots.map((sl,i)=>control('g6-slot',String(i),sl.name,sl===selected)).join('')}</div>`;
  const placed=g.slots[selected.name]||[];card(selected.name,x,y,w,height,selected.name,`<b>${sayButton(selected.name)}</b><div class="g6-placed">${placed.map(w=>`<div>${picture(w,sprite(w))}${sayButton(w)}${control('g6-remove',selected.name+'|'+w,'取回')}</div>`).join('')||'<small>选道具或拖到这里</small>'}</div>`,{ready:placed.length>0});
  const size=ui.compact?2:4,pages=Math.ceil(selected.choices.length/size),page=Math.min(pages-1,ui.trayPage||0);
  selected.choices.slice(page*size,(page+1)*size).forEach((word,i)=>objects.push(object('g6-token-'+word,sprite(word),ui.compact?250+i*475:150+i*220,545,ui.compact?210:170,95,{label:word,speech:word,draggable:true,item:word,...(colors[word]?{color:colors[word]}:{})})));
  if(pages>1)actions.push({name:'tray-page',value:Math.max(0,page-1),text:'上一组道具',disabled:page===0},{name:'tray-page',value:Math.min(pages-1,page+1),text:`下一组道具 · ${page+1}/${pages}`,disabled:page===pages-1});
 }
 if(r.mode==='shop')decor+=`<div class="g6-bank">游戏币：${g.bank} / 12 · 本单 ${r.price}</div>`;
 return {objects,zones,decor,actions};
}
